### ISSUE TITLE
Request of adding new works

### ISSUE THREAD

**Issue by youhua97** [archersama/awesome-recommend-system-pretraining-papers#14]
Hi,

We recently came across your project and were impressed by its scope and objectives. We believe that our research papers could be a valuable addition to your project as references:

 1 NineRec: A Benchmark Dataset Suite for Evaluating Transferable Recommendation
        Link: https://arxiv.org/pdf/2309.07705.pdf
  2 A Content-Driven Micro-Video Recommendation Dataset at Scale
        Link: https://arxiv.org/pdf/2309.15379.pdf

We kindly request you to consider including our papers in your project. If you require any additional information or have any questions, please do not hesitate to contact us.

**Comment by archersama** [comment]
thanks ， i added it

**Comment by youhua97** [comment]
Thanks a lot!

XiangyangLi ***@***.***> 于2024年3月15日周五 15:25写道：
