### ISSUE TITLE
url misplace

### ISSUE THREAD

**Issue by fs302** [archersama/awesome-recommend-system-pretraining-papers#2]
Pre-train, Prompt and Recommendation: A Comprehensive Survey of Language Modelling Paradigm Adaptations in Recommender Systems, arxiv 2022, [[paper]](https://arxiv.org/pdf/2203.15876.pdf)

paper url is incorrect. maybe the correct url is https://arxiv.org/abs/2107.13586

**Comment by archersama** [comment]
update
