### ISSUE TITLE
A New Empirical Evaluation of ChatGPT for Recommender System

### ISSUE THREAD

**Issue by KID-22** [archersama/awesome-recommend-system-pretraining-papers#3]
Hello! Our new work titled ‘Uncovering ChatGPT’s Capabilities in Recommender Systems’ has been released and can be found at https://arxiv.org/pdf/2305.02182.pdf. We have also open-sourced our code and detailed results at https://github.com/rainym00d/LLM4RS. We kindly request that please add it to this repository. Thank you!

**Comment by archersama** [comment]
added

**Comment by KID-22** [comment]
Thank you very much!
