### ISSUE TITLE
Adding a new paper to the "Sequential / Session-Based Recommendation" section

### ISSUE THREAD

**Issue by gimpong** [archersama/awesome-recommend-system-pretraining-papers#8]
Hi Xiangyang,

Thanks for your awesome repository! I believe it will help many researchers gain insights into the latest PLM-based techniques and benefit the RS community.

I am happy to announce our paper, "MISSRec: Pre-training and Transferring Multi-modal Interest-aware Sequence Representation for Recommendation" (https://arxiv.org/abs/2308.11175), on ACM MM 2023. This paper is about integrating multi-modal information (using the pre-trained CLIP model) into behavior sequence representation to support universal recommendation. The data and code are also available at https://github.com/gimpong/MM23-MISSRec. 

If the paper falls within the scope of this repository, I would appreciate it if you considered including it in the paper list. :)

Kind regards,
Jinpeng

**Comment by archersama** [comment]
add it
