### ISSUE TITLE
Adding a LLM-based RecSys paper to "Large Language Models for Recommendation"

### ISSUE THREAD

**Issue by Yueeeeeeee** [archersama/awesome-recommend-system-pretraining-papers#9]
Hi @archersama,

Thank you for maintaining this repo of LLM Recsys, we recently release a workshop paper call LlamaRec for LLM-based sequential recommender. The paper can be found at https://github.com/Yueeeeeeee/LlamaRec/blob/main/media/paper.pdf (ArXiv will be available soon) and the code can be found at: https://github.com/Yueeeeeeee/LlamaRec

Would you mind adding this work to your repo, under the section "Large Language Models for Recommendation"? Thank you!

**Comment by archersama** [comment]
welcome add a pull request when arxiv version is ready

**Comment by Yueeeeeeee** [comment]
Added new pull request:)
